// Generated by https://quicktype.io

export interface MostReadPeriod {
  most_read: MostReadPeriodElement[];
}

export interface MostReadPeriodElement {
  adult_content: number;
  id_serie: number;
  id_release: number;
  id_chapter: number;
  series_image: string;
  series_image_thumb: string;
  series_image_avif: string;
  series_image_thumb_avif: string;
  series_name: string;
  chapter_number: string;
  date: string;
  serie_link: string;
  link: string;
}
