// Generated by https://quicktype.io

export interface MostRead {
  most_read: MostReadElement[];
}

export interface MostReadElement {
  id_serie: number;
  serie_name: string;
  cover: string;
  cover_thumb: string;
  cover_avif: string;
  cover_thumb_avif: string;
  link: string;
}
