// Generated by https://quicktype.io

export interface Release {
  releases: ReleaseElement[];
}

export interface ReleaseElement {
  date: string;
  dateString: string;
  date_created: string;
  id_serie: number;
  name: string;
  image: string;
  image_thumb: string;
  image_avif: string;
  image_thumb_avif: string;
  range: string;
  chapters: ReleaseChapter[];
  link: string;
}

export interface ReleaseChapter {
  url: string;
  number: string;
  date_created: string;
}

export interface Scan {
  id_scanlator: number;
  name: string;
  link: string;
}
